src/Entity/Asso.php
<?php

namespace App\Entity;

use App\Repository\AssoRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: AssoRepository::class)]
class Asso
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(length: 255)]
    private ?string $img_asso = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getImgAsso(): ?string
    {
        return $this->img_asso;
    }

    public function setImgAsso(string $img_asso): static
    {
        $this->img_asso = $img_asso;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }
}

src/Form/AssoType.php
<?php

namespace App\Form;

use App\Entity\Asso;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Validator\Constraints\File;

class AssoType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name')
            ->add('description')
            ->add('img_asso', FileType::class, [
                'label' => 'Photo de l’article',
                'mapped' => false,
                'required' => false,
                'constraints' => [
                new File([
                'maxSize' => '5000k',
                'mimeTypes' => [
                'image/*',
                ],
                'mimeTypesMessage' => 'Image trop lourde',
                ])
                ],
                ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Asso::class,
        ]);
    }
}

src/Controller/AssoController.php
<?php

namespace App\Controller;

use App\Entity\Asso;
use App\Form\AssoType;
use App\Repository\AssoRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/asso')]
class AssoController extends AbstractController
{
    #[Route('/', name: 'app_asso_index', methods: ['GET'])]
    public function index(AssoRepository $assoRepository): Response
    {
        return $this->render('asso/index.html.twig', [
            'assos' => $assoRepository->findAll(),
        ]);
    }

    // #[Route('/new', name: 'app_asso_new', methods: ['GET', 'POST'])]
    // public function new(Request $request, EntityManagerInterface $entityManager): Response
    // {
    //     $asso = new Asso();
    //     $form = $this->createForm(AssoType::class, $asso);
    //     $form->handleRequest($request);

    //     if ($form->isSubmitted() && $form->isValid()) {
    //         $entityManager->persist($asso);
    //         $entityManager->flush();

    //         return $this->redirectToRoute('app_asso_index', [], Response::HTTP_SEE_OTHER);
    //     }

    //     return $this->render('asso/new.html.twig', [
    //         'asso' => $asso,
    //         'form' => $form,
    //     ]);
    // }

    #[Route('/{id}', name: 'app_asso_show', methods: ['GET'])]
    public function show(Asso $asso): Response
    {
        return $this->render('asso/show.html.twig', [
            'asso' => $asso,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_asso_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Asso $asso, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(AssoType::class, $asso);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_asso_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('asso/edit.html.twig', [
            'asso' => $asso,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_asso_delete', methods: ['POST'])]
    public function delete(Request $request, Asso $asso, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$asso->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($asso);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_asso_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/asso/_delete_form.html.twig
<form method="post" action="{{ path('app_asso_delete', {'id': asso.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ asso.id) }}">
    <button class="btn">Delete</button>
</form>

templates/asso/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/asso/edit.html.twig
{% extends 'admin.html.twig' %}

{% block title %}Edit Asso{% endblock %}

{% block body %}
    <h1>Edit Asso</h1>

    {{ include('asso/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_asso_index') }}">back to list</a>

    {# {{ include('asso/_delete_form.html.twig') }} #}
{% endblock %}

templates/asso/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Asso index
{% endblock %}

{% block body %}
 <div class="container-fluid text-center">
		<h1>Asso index</h1>
        <span><a href="{{ path('app_asso_new') }}">Create new</a></span>
		<div class="d-md-flex flex-md-wrap bg-primary">
			{% for asso in assos %}
			<div class="flex-md-fill col-md-3 card m-4 ">
					<div class="card-body">
						<span>{{ asso.id }}</span>
						<h2 class="card-title">{{ asso.name }}</h2>
						<p class="card-text">{{ asso.description }}</p>
						{# <span>{{ asso.img_asso }}</span> #}
						<div class="card-footer">
							<span>
								<a href="{{ path('app_asso_show', {'id': asso.id}) }}">show</a>
							</span>
							<span>
								<a href="{{ path('app_asso_edit', {'id': asso.id}) }}">edit</a>
							</span>
						</div>
					</div>
				</div>
			{% else %}
				<span>no records found</span>
			</div>
		{% endfor %}
	</div>
{% endblock %}

templates/asso/new.html.twig
{% extends 'admin.html.twig' %}

{% block title %}New Asso{% endblock %}

{% block body %}
    <h1>Create new Asso</h1>

    {{ include('asso/_form.html.twig') }}

    <a href="{{ path('app_asso_index') }}">back to list</a>
{% endblock %}

templates/asso/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Asso
{% endblock %}

{% block body %}
	<h1>Asso</h1>

	<table class="table">
		<tbody>
			<tr>
				<th>Id</th>
				<td>{{ asso.id }}</td>
			</tr>
			<tr>
				<th>Name</th>
				<td>{{ asso.name }}</td>
			</tr>
			<tr>
				<th>Img_asso</th>
				<td>{{ asso.imgAsso }}</td>
			</tr>
			<tr>
				<th>Description</th>
				<td>{{ asso.description }}</td>
			</tr>
		</tbody>
	</table>
    <a href="{{ path('app_asso_index') }}">back to list</a>
    
	{% if is_granted('ROLE_ADMIN') %}
		<a href="{{ path('app_asso_edit', {'id': asso.id}) }}">edit</a>
		{{ include('asso/_delete_form.html.twig') }}
	{% endif %}
{% endblock %}