src/Entity/Members.php
<?php

namespace App\Entity;

use App\Repository\MembersRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: MembersRepository::class)]
class Members
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column(length: 255)]
    private ?string $name_member = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $img_member = null;

    /**
     * @var Collection<int, Teams>
     */
    #[ORM\ManyToMany(targetEntity: Teams::class, inversedBy: 'members')]
    private Collection $teams;

    public function __construct()
    {
        $this->teams = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getNameMember(): ?string
    {
        return $this->name_member;
    }

    public function setNameMember(string $name_member): static
    {
        $this->name_member = $name_member;

        return $this;
    }

    public function getImgMember(): ?string
    {
        return $this->img_member;
    }

    public function setImgMember(?string $img_member): static
    {
        $this->img_member = $img_member;

        return $this;
    }

    /**
     * @return Collection<int, Teams>
     */
    public function getTeams(): Collection
    {
        return $this->teams;
    }

    public function addTeam(Teams $team): static
    {
        if (!$this->teams->contains($team)) {
            $this->teams->add($team);
        }

        return $this;
    }

    public function removeTeam(Teams $team): static
    {
        $this->teams->removeElement($team);

        return $this;
    }
}

src/Entity/Sections.php
<?php

namespace App\Entity;

use App\Repository\SectionsRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SectionsRepository::class)]
class Sections
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nameSection = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $img_section = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNameSection(): ?string
    {
        return $this->nameSection;
    }

    public function setNameSection(string $nameSection): static
    {
        $this->nameSection = $nameSection;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getImgSection(): ?string
    {
        return $this->img_section;
    }

    public function setImgSection(?string $img_section): static
    {
        $this->img_section = $img_section;

        return $this;
    }
}

src/Entity/Teams.php
<?php

namespace App\Entity;

use App\Repository\TeamsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: TeamsRepository::class)]
class Teams
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name_team = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $img_team = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    /**
     * @var Collection<int, Members>
     */
    #[ORM\ManyToMany(targetEntity: Members::class, mappedBy: 'teams')]
    private Collection $members;

    public function __construct()
    {
        $this->members = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNameTeam(): ?string
    {
        return $this->name_team;
    }

    public function setNameTeam(string $name_team): static
    {
        $this->name_team = $name_team;

        return $this;
    }

    public function getImgTeam(): ?string
    {
        return $this->img_team;
    }

    public function setImgTeam(?string $img_team): static
    {
        $this->img_team = $img_team;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    /**
     * @return Collection<int, Members>
     */
    public function getMembers(): Collection
    {
        return $this->members;
    }

    public function addMember(Members $member): static
    {
        if (!$this->members->contains($member)) {
            $this->members->add($member);
            $member->addTeam($this);
        }

        return $this;
    }

    public function removeMember(Members $member): static
    {
        if ($this->members->removeElement($member)) {
            $member->removeTeam($this);
        }

        return $this;
    }
}

src/Controller/AdministrationController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\HttpFoundation\Request;
use Doctrine\ORM\EntityManagerInterface;
use App\Entity\Members;
use App\Form\MembersType;
use App\Entity\Asso;
use App\Form\AssoType;
use App\Entity\Sections;
use App\Form\SectionsType;
use App\Entity\Teams;
use App\Form\TeamsType;
use App\Repository\MembersRepository;
use App\Repository\AssoRepository;
use App\Repository\SectionsRepository;
use App\Repository\TeamsRepository;


#[Route('/administration')]
class AdministrationController extends AbstractController
{
    #[Route('/', name: 'app_administration')]
    public function index(): Response
    {
        $this->denyAccessUnlessGranted('ROLE_USER');
        return $this->render('administration/index.html.twig', [
            'administrateur_name' => 'Romain',
        ]);
    }
    
    //crud administration Asso//

    #[Route('/asso', name: 'app_admin_asso_index', methods: ['GET'])]
    public function indexAsso(AssoRepository $assoRepository): Response
    {
        $this->denyAccessUnlessGranted('ROLE_USER');
        return $this->render('administration/adminAsso.html.twig', [
            'assos' => $assoRepository->findAll(),
        ]);
    }

    #[Route('/asso/new', name: 'app_admin_asso_new', methods: ['GET', 'POST'])]
    public function newAsso(Request $request, EntityManagerInterface $entityManager): Response
    {
        $asso = new Asso();
        $form = $this->createForm(AssoType::class, $asso);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($asso);
            $entityManager->flush();

            return $this->redirectToRoute('app_admin_asso_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('asso/new.html.twig', [
            'asso' => $asso,
            'form' => $form,
        ]);
    }

    #[Route('/asso/{id}/edit', name: 'app_admin_asso_edit', methods: ['GET', 'POST'])]
    public function editAsso(Request $request, Asso $asso, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(AssoType::class, $asso);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_admin_asso_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('asso/edit.html.twig', [
            'asso' => $asso,
            'form' => $form,
        ]);
    }

    #[Route('/asso/{id}', name: 'app_admin_asso_delete', methods: ['POST'])]
    public function deleteAsso(Request $request, Asso $asso, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete' . $asso->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($asso);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_admin_asso_index', [], Response::HTTP_SEE_OTHER);
    }

    //crud administration sections//

    #[Route('/sections', name: 'app_admin_sections_index', methods: ['GET'])]
    public function indexSections(SectionsRepository $sectionsRepository): Response
    {
        $this->denyAccessUnlessGranted('ROLE_USER');
        return $this->render('administration/adminSections.html.twig', [
            'sections' => $sectionsRepository->findAll(),
        ]);
    }

    #[Route('/sections/new', name: 'app_admin_sections_new', methods: ['GET', 'POST'])]
    public function newSections(Request $request, EntityManagerInterface $entityManager): Response
    {
        $this->denyAccessUnlessGranted('ROLE_USER');
        $section = new Sections();
        $form = $this->createForm(SectionsType::class, $section);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($section);
            $entityManager->flush();

            return $this->redirectToRoute('app_admin_sections_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('sections/new.html.twig', [
            'section' => $section,
            'form' => $form,
        ]);
    }

    #[Route('/sections/{id}/edit', name: 'app_admin_sections_edit', methods: ['GET', 'POST'])]
    public function editSections(Request $request, Sections $section, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(SectionsType::class, $section);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_admin_sections_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('sections/edit.html.twig', [
            'section' => $section,
            'form' => $form,
        ]);
    }

    #[Route('/sections/{id}', name: 'app_sections_delete', methods: ['POST'])]
    public function delete(Request $request, Sections $section, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$section->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($section);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_sections_index', [], Response::HTTP_SEE_OTHER);
    }

    //crud administration Members//

    #[Route('/members', name: 'app_admin_members_index', methods: ['GET'])]
    public function indexMembers(MembersRepository $membersRepository): Response
    {
        $this->denyAccessUnlessGranted('ROLE_USER');
        return $this->render('administration/adminMembers.html.twig', [
            'members' => $membersRepository->findAll(),
        ]);
    }

    #[Route('/members/new', name: 'app_admin_members_new', methods: ['GET', 'POST'])]
    public function newMembers(Request $request, EntityManagerInterface $entityManager): Response
    {
        $this->denyAccessUnlessGranted('ROLE_USER');
        $member = new Members();
        $form = $this->createForm(MembersType::class, $member);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($member);
            $entityManager->flush();

            return $this->redirectToRoute('app_admin_members_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('members/new.html.twig', [
            'member' => $member,
            'form' => $form,
        ]);
    }

    #[Route('/members/{id}/edit', name: 'app_admin_members_edit', methods: ['GET', 'POST'])]
    public function editMembers(Request $request, Members $member, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(MembersType::class, $member);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_admin_members_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('members/edit.html.twig', [
            'member' => $member,
            'form' => $form,
        ]);
    }

    #[Route('/members/{id}', name: 'app_admin_members_delete', methods: ['POST'])]
    public function deleteMembers(Request $request, Members $member, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete' . $member->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($member);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_admin_members_index', [], Response::HTTP_SEE_OTHER);
    }

    //crud administration Teams//

    #[Route('/teams', name: 'app_adminteams_index', methods: ['GET'])]
    public function indexTeams(TeamsRepository $teamsRepository): Response
    {
        $this->denyAccessUnlessGranted('ROLE_USER');
        return $this->render('administration/adminTeams.html.twig', [
            'teams' => $teamsRepository->findAll(),
        ]);
    }

    #[Route('/teams/new', name: 'app_admin_teams_new', methods: ['GET', 'POST'])]
    public function newTeams(Request $request, EntityManagerInterface $entityManager): Response
    {
        $this->denyAccessUnlessGranted('ROLE_USER');
        $team = new Teams();
        $form = $this->createForm(TeamsType::class, $team);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($team);
            $entityManager->flush();

            return $this->redirectToRoute('app_admin_teams_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('teams/new.html.twig', [
            'team' => $team,
            'form' => $form,
        ]);
    }

    #[Route('/teams/{id}/edit', name: 'app_admin_teams_edit', methods: ['GET', 'POST'])]
    public function editTeams(Request $request, Teams $team, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(TeamsType::class, $team);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_admin_teams_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('teams/edit.html.twig', [
            'team' => $team,
            'form' => $form,
        ]);
    }

    #[Route('/teams/{id}', name: 'app_teams_delete', methods: ['POST'])]
    public function deleteTeams(Request $request, Teams $team, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$team->getId(), $request->getPayload()->getString('_token'))) {

templates/administration/adminAsso.html.twig
{% extends 'admin.html.twig' %}

{% block title %}Hello Administration de l'asso
{% endblock %}

{% block body %}
	<h1 class="text-light">Administration de l'asso</h1>
	<button>
		<a href="{{ path('app_admin_asso_new') }}">Creer une nouvelle asso</a>
	</button>
	<table class="table">
		<thead>
			<tr>
				<th>Id</th>
				<th>Name</th>
				<th>Description</th>
				<th>actions</th>
			</tr>
		</thead>
		<tbody>
			{% for asso in assos %}
				<tr>
					<td>{{ asso.id }}</td>
					<td>{{ asso.name }}</td>
					<td>{{ asso.description }}</td>
					<td>
						<a href="{{ path('app_asso_show', {'id': asso.id}) }}">show</a>
						<a href="{{ path('app_admin_asso_edit', {'id': asso.id}) }}">edit</a>
					</td>
				</tr>
			{% else %}
				<tr>
					<td colspan="5">no records found</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>


{% endblock %}

templates/administration/adminMembers.html.twig
{% extends 'admin.html.twig' %}

{% block title %}Administration des membres!
{% endblock %}

{% block body %}
	<h1 class="text-light">Administration des membres</h1>
	<button>
		<a href="{{ path('app_admin_members_new') }}">Créer un nouveau membre</a>
		<button>
			<a href="/members/">Voir les Membres</a>
		</button>
	</button>
	<table class="table">
		<thead>
			<tr>
				<th>Id</th>
				<th>Name_member</th>
				<th>Description</th>
				<th>Img_member</th>
				<th>actions</th>
			</tr>
		</thead>
		<tbody>
			{% for member in members %}
				<tr>
					<td>{{ member.id }}</td>
					<td>{{ member.nameMember }}</td>
					<td>{{ member.description }}</td>
					<td>{{ member.imgMember }}</td>
					<td>
						<a href="{{ path('app_members_show', {'id': member.id}) }}">show</a>
						<a href="{{ path('app_admin_members_edit', {'id': member.id}) }}">edit</a>
						{# <a href="{{ path('app_admin_members_delete', {'id': member.id}) }}">delete</a> #}
					</td>
				</tr>
			{% else %}
				<tr>
					<td colspan="5">no records found</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>


{% endblock %}

templates/administration/adminSections.html.twig
{% extends 'admin.html.twig' %}

{% block title %}Hello Administration des sections!
{% endblock %}

{% block body %}
	<h1 class="text-light">Administration des sections</h1>
	<button>
		<a href="{{ path('app_admin_sections_new') }}">Créer une nouvelle technique</a>
		<button>
			<a href="/sections/">Voir les techniques</a>
		</button>
	</button>
	<table class="table">
		<thead>
			<tr>
				<th>Id</th>
				<th>NameSection</th>
				<th>Description</th>
				<th>Img_section</th>
				<th>actions</th>
			</tr>
		</thead>
		<tbody>
			{% for section in sections %}
				<tr>
					<td>{{ section.id }}</td>
					<td>{{ section.nameSection }}</td>
					<td>{{ section.description }}</td>
					<td>{{ section.imgSection }}</td>
					<td>
						<a href="{{ path('app_sections_show', {'id': section.id}) }}">show</a>
						<a href="{{ path('app_admin_sections_edit', {'id': section.id}) }}">edit</a>
					</td>
				</tr>
			{% else %}
				<tr>
					<td colspan="5">no records found</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>


{% endblock %}

templates/administration/adminTeams.html.twig
{% extends 'admin.html.twig' %}

{% block title %}Hello Administration des teams!{% endblock %}

{% block body %}
<h1 class="text-light">Administration des teams</h1>
<button><a href="{{ path('app_teams_new') }}">Créer une nouvelle team</a></button>
<button><a href="/teams/">Voir les teams</a></button>
<table class="table">
    <thead>
        <tr>
            <th>Id</th>
            <th>Name_team</th>
            <th>Img_team</th>
            <th>Description</th>
            <th>actions</th>
        </tr>
    </thead>
    <tbody>
    {% for team in teams %}
        <tr>
            <td>{{ team.id }}</td>
            <td>{{ team.nameTeam }}</td>
            <td>{{ team.imgTeam }}</td>
            <td>{{ team.description }}</td>
            <td>
                <a href="{{ path('app_teams_show', {'id': team.id}) }}">show</a>
                <a href="{{ path('app_admin_teams_edit', {'id': team.id}) }}">edit</a>
            </td>
        </tr>
    {% else %}
        <tr>
            <td colspan="5">no records found</td>
        </tr>
    {% endfor %}
    </tbody>
</table>




{% endblock %}

templates/administration/index.html.twig
{% extends 'admin.html.twig' %}

{% block title %}Hello {{administrateur_name}}!{% endblock %}

{% block body %}
<h1 class="text-light">Administration du site</h1>
<p>Bienvenue sur l'espace administration du site.</p>



{% endblock %}